### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by tnusraddinov** [tntrung/impSDM#3]
Hi, thank you for your implementation, but I get error while training as bellow. I did every thing as written in readme.md file.

...
Stage: 1 - Image: 224
Stage: 1 - Image: 225
Subscripted assignment dimension mismatch.

Error in local_descriptors (line 55)
        desc(ipts,:) = hog(im,xy(ipts,:),dsize);

Error in learn_single_regressor (line 160)
            tmp = local_descriptors( cropIm_scale, ...

Error in run_training (line 42)
        [R,new_init_shape,rms(icascade)] = learn_single_regressor( ...

**Comment by tntrung** [comment]
Could you please let me know which database you are using for training?

The problem happens may be the number columns of desc is not matched well with the descriptor extracted using hog function.

**Comment by tntrung** [comment]
Or the file ground-truth loaded for the image is not good, causes the problem when calling xy(ipts,:).

**Comment by tnusraddinov** [comment]
I used LFPW database.

**Comment by tnusraddinov** [comment]
While testing after 12th image I get this (same) error: 

rms = 0.10891
Image: 10
rms = 0.081873
Image: 11
rms = 0.49941
Image: 12
Subscripted assignment dimension mismatch.

Error in local_descriptors (line 55)
        desc(ipts,:) = hog(im,xy(ipts,:),dsize);

Error in cascaded_regress (line 33)
    desc = local_descriptors(cropIm_scale, ...

Error in face_alignment (line 43)
    aligned_shape(ir,:) = cascaded_regress( ShapeModel, ...

Error in do_testing (line 44)
    aligned_shape = face_alignment( ShapeModel, DataVariation, ...

**Comment by tntrung** [comment]
Hi,  I've just tested on my machine and no problem with LFPW. Could you please check if the value of xy(ipts,:) is OK, may be problem because the value xy is null because the problem when loading the ground-truth file.

**Comment by tntrung** [comment]
If you change something in hog(), function. Please, make sure (modified by you) the the initial of desc is the same size with hog feature. Sorry for this inconvenience.

**Comment by tnusraddinov** [comment]
In LFPW database train folder in first 11 images hog function returns 62x1 vector while in 12th image hog returns 124x1 vector, then assignment dimension mismatch appears in desc variable. Why does hog return different size vectors and how to fix it?

**Comment by tntrung** [comment]
You can check it in function: common/desc/hog.m. It sounds strange that the Hog feature is changed. Maybe the input image of Hog function has some problems. Please check if its size is 64x64. It does not happen on my machine?? Thanks.

**Comment by tntrung** [comment]
Hello, I found and fixed the problem.

**Comment by tnusraddinov** [comment]
Thanks
