### ISSUE TITLE
How to get the pts file and it includes 68 feature points.

### ISSUE THREAD

**Issue by SSLpython** [tntrung/impSDM#8]
Hi !
    I'm sorry to bother you, but there is a problem with your code we have some questions confused me for a long time. I carefully read your code, I found your database has a PTS file, it contains 68 feature points. I've been thinking about when there is no the PTS file how can we run?
   I  do the experiment with their own data but i haven't a result, the reason is that I can't get a PTS file. I tried to manually tag within the coordinates of facial feature points on the PTS files, but the pictures too much, I a person cannot complete such a big task.  How do you know the PTS file of each face image automatically get？

**Comment by tntrung** [comment]
Hi, there is no way to avoid the manual annotation for PTS, but I recommend that you can test your method with standard data-sets providing available ground-truth.
